CREATE TABLE tareas (
  id SERIAL PRIMARY KEY,
  titulo VARCHAR(255) UNIQUE NOT NULL,
  descripcion TEXT,
  usuario_id INTEGER REFERENCES usuarios(id), ON DELETE CASCADE,
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuarios (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  gravatar VARCHAR(255)
);

